// Date: 2015/01/17 21:54:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package tsuteto.spelunker.block.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * Model for Spelunker Portal Block
 *
 * @author Originally created by 超田中氏 (Tyotanaka) - Thx!
 */
public class ModelSpelunkerPortalStage extends ModelBase
{
    //fields
    ModelRenderer stage1;
    ModelRenderer stage2;
    ModelRenderer stage3;

    public ModelSpelunkerPortalStage()
    {
        textureWidth = 64;
        textureHeight = 64;

        stage1 = new ModelRenderer(this, 0, 27);
        stage1.addBox(0F, 0F, 0F, 10, 2, 10);
        stage1.setRotationPoint(-5F, -8F, -5F);
        stage1.setTextureSize(64, 64);
        stage1.mirror = true;
        setRotation(stage1, 0F, 0F, 0F);
        stage2 = new ModelRenderer(this, 20, 5);
        stage2.addBox(0F, 0F, 0F, 8, 11, 8);
        stage2.setRotationPoint(-4F, -6F, -4F);
        stage2.setTextureSize(64, 64);
        stage2.mirror = true;
        setRotation(stage2, 0F, 0F, 0F);
        stage3 = new ModelRenderer(this, 0, 39);
        stage3.addBox(0F, 0F, 0F, 16, 3, 16);
        stage3.setRotationPoint(-8F, 5F, -8F);
        stage3.setTextureSize(64, 64);
        stage3.mirror = true;
        setRotation(stage3, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        stage1.render(f5);
        stage2.render(f5);
        stage3.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
