package tsuteto.spelunker;

import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.versioning.DefaultArtifactVersion;

public class ModInfo
{
    public static void load(ModMetadata meta)
    {
        meta.modId = SpelunkerMod.modId;
        meta.name = "SPELUNKER MOD";
        meta.description = "かつてファミコンで大活躍し、今に復活してなおその名を馳せる洞窟探検の偉大なる先人「スペランカー」の類い希なる能力を与えるMODです。\n\n" +
                "Gives you the unique skills of the great forerunner Spelunker, who once made a splendid action on NES and is still gaining popularity after his revival.";
        meta.version = "3.0";
        meta.credits = "Feature support by MMMさん, 綾繁さん. " +
                "PlayerAPI support by Divisor. Spelunker model by 超田中さん. " +
                "Playing video and bug report by ミヤビさん, Silent7さん, ぶりすさん. Thanks to them all!";
        meta.logoFile = "assets/spelunker/logo.png";
        meta.url = "http://forum.minecraftuser.jp/viewtopic.php?f=13&t=1014";
        meta.updateUrl = "https://dl.dropboxusercontent.com/u/14577828/mcmod/update/spelunkermod.json";
        meta.authorList.add("つてと (Tsuteto)");
        meta.dependencies.add(new DefaultArtifactVersion("PlayerAPI pack", true));

        meta.autogenerated = false;
    }

}
